
if __name__ == "__main__":
    with open("lib交集.txt", mode = 'w') as file:
        lines = "total:128; 系统库:12; GBIM库:9; GMP库:34; GlodonResource库:24; GTJDeps库:7; Qt库:10; RelWithDebInfo库:32\n"
        lines += "系统库:\n"
        lines += "AdvAPI32.lib\n"
        lines += "ComDlg32.lib\n"
        lines += "Gdi32.lib\n"
        lines += "kernel32.lib\n"
        lines += "Ole32.lib\n"
        lines += "OleAut32.lib\n"
        lines += "Psapi.lib\n"
        lines += "shell32.lib\n"
        lines += "User32.lib\n"
        lines += "Uuid.lib\n"
        lines += "Version.lib\n"
        lines += "WinSpool.lib\n"
        lines += "\n"
        
        lines += "GBIM库:\n"
        lines += "ArchiAlgo.lib\n"
        lines += "CmdCore.lib\n"
        lines += "Common.lib\n"
        lines += "Geometry.lib\n"
        lines += "GGPViewerProxy.lib\n"
        lines += "GMath.lib\n"
        lines += "RichText.lib\n"
        lines += "ViewCore.lib\n"
        lines += "ViewManager.lib\n"
        lines += "\n"
        
        lines += "GMP库:\n"
        lines += "curl.lib\n"
        lines += "DBoperations.lib\n"
        lines += "GCADModel.lib\n"
        lines += "GCCSCloudService32.lib\n"
        lines += "GFcClasses.lib\n"
        lines += "GFcExporter.lib\n"
        lines += "GFcImporter.lib\n"
        lines += "GMCommon.lib\n"
        lines += "GMModel.lib\n"
        lines += "GMPCloud.lib\n"
        lines += "GMPCloudConfig.lib\n"
        lines += "GMPCloudLogin.lib\n"
        lines += "GMPCloudService.lib\n"
        lines += "GMPCloudStorage.lib\n"
        lines += "GMPCloudUtils.lib\n"
        
        lines += "GMPControls.lib\n"
        lines += "GMPCore.lib\n"
        lines += "GMPGeometry.lib\n"
        lines += "GMPProject.lib\n"
        lines += "GMPSharingModel.lib\n"
        lines += "GMPUbc.lib\n"
        lines += "GMPWidgets.lib\n"
        lines += "GTCadImporter.lib\n"
        lines += "GTTchEntity_19.7src_14.lib\n"
        lines += "libapr-1.lib\n"
        lines += "libaprutil-1.lib\n"
        lines += "Log.lib\n"
        lines += "MDCache.lib\n"
        lines += "MDCmdLog.lib\n"
        lines += "MDCommon.lib\n"
        lines += "MDScript.lib\n"
        lines += "objectbuf.lib\n"
        lines += "VDECore.lib\n"
        lines += "VectorDrawing.lib\n"
        lines += "\n"
        
        lines += "GlodonResource库:\n"
        lines += "GEPEngine.lib\n"
        lines += "GLDCrypt.lib\n"
        lines += "GLDPrivateCalledPlatform.lib\n"
        lines += "GLDStyles.lib\n"
        lines += "GLDTableView.lib\n"
        lines += "GLDTechPlatform.lib\n"
        lines += "GLDThemeEngine.lib\n"
        lines += "GLDWidget.lib\n"
        lines += "GLDXLS.lib\n"
        lines += "GLDXML.lib\n"
        lines += "GLDZIP.lib\n"
        lines += "GMPRibbonStyle.lib\n"
        lines += "GMPUIExtends.lib\n"
        lines += "GSCCore.lib\n"
        lines += "GSP.lib\n"
        lines += "GUC.lib\n"
        lines += "libcurl.lib\n"
        lines += "libtcmalloc_minimal.lib\n"
        lines += "libxl.lib\n"
        lines += "log4cplusU.lib\n"
        lines += "qtnchart2.lib\n"
        lines += "qtnribbon3.lib\n"
        lines += "sqlite3.lib\n"
        lines += "VMProtectSDK32.lib\n"
        lines += "\n"
        
        lines += "GTJDeps库:\n"
        lines += "libevent.lib\n"
        lines += "libevent_core.lib\n"
        lines += "libevent_extras.lib\n"
        lines += "libzmq.lib\n"
        lines += "lua535.lib\n"
        lines += "mxml1.lib\n"
        lines += "oss_c_sdk.lib\n"
        lines += "\n"
        
        lines += "Qt库:\n"
        lines += "Qt5AxBase.lib\n"
        lines += "Qt5AxContainer.lib\n"
        lines += "Qt5Core.lib\n"
        lines += "Qt5Gui.lib\n"
        lines += "Qt5Network.lib\n"
        lines += "Qt5Qml.lib\n"
        lines += "Qt5Quick.lib\n"
        lines += "Qt5Widgets.lib\n"
        lines += "Qt5Xml.lib\n"
        lines += "Qt5XmlPatterns.lib\n"
        lines += "\n"
        
        lines += "RelWithDebInfo库:\n"
        lines += "GBQIntegration.lib\n"
        lines += "GCLDataService.lib\n"
        lines += "GCLTableInput.lib\n"
        lines += "GCLWork.lib\n"
        lines += "GFCCommon.lib\n"
        lines += "GGDB.lib\n"
        lines += "GGDBDataAwareCtrl.lib\n"
        lines += "GGJBarViewer.lib\n"
        lines += "GGJCalcCommon.lib\n"
        lines += "GGJSectionBarEditor.lib\n"
        lines += "GGJTableInput.lib\n"
        lines += "GLDCommon.lib\n"
        lines += "GTJBarInfoModel.lib\n"
        lines += "GTJBodyBuilder.lib\n"
        lines += "GTJCalcData.lib\n"
        lines += "GTJCalcDomainModel.lib\n"
        lines += "GTJCalcExtension.lib\n"
        lines += "GTJCalcUtils.lib\n"
        lines += "GTJCloudRule.lib\n"
        lines += "GTJCloudRulePlugin.lib\n"
        lines += "GTJDomainModel.lib\n"
        lines += "GTJGeneralAlgorithm.lib\n"
        lines += "GTJGeneralUtility.lib\n"
        lines += "GTJModelCmdState.lib\n"
        lines += "GTJModelDao.lib\n"
        lines += "GTJModelExtension.lib\n"
        lines += "GTJSharingPlugin.lib\n"
        lines += "GTJTableInput.lib\n"
        lines += "GTJTableInputCommon.lib\n"
        lines += "GTJUIExtension.lib\n"
        lines += "GTJUIModule.lib\n"
        lines += "VectorDrawingEditor.lib\n"
        lines += "\n"
        
        file.write(lines)
        
    with open("lib差集小-大.txt", mode = 'w') as file:
        lines = "total:2; GlodonResource库:1; Qt库:1\n"
        lines += "GlodonResource库:\n"
        lines += "GSPKeyLib.lib\n"
        lines += "\n"
        
        lines += "Qt库:\n"
        lines += "qtmain.lib\n"
        lines += "\n"
        
        file.write(lines)
        
    with open("lib差集大-小.txt", mode = 'w') as file:
        lines = "total:37; 系统库:4; GBIM库:1; GMP库:2; GlodonResource库:5; GTJDeps库:4; Qt库:2; RelWithDebInfo库:19\n"
        lines += "系统库:\n"
        lines += "comsupp.lib\n"
        lines += "legacy_stdio_definitions.lib\n"
        lines += "WinInet.lib\n"
        lines += "WS2_32.lib\n"
        lines += "\n"
        
        lines += "GBIM库:\n"
        lines += "sdt.lib\n"
        lines += "\n"
        
        lines += "GMP库:\n"
        lines += "Dll7zip.lib\n"
        lines += "GCADIdentification.lib\n"
        lines += "\n"
        
        lines += "GlodonResource库:\n"
        lines += "GRPCommon.lib\n"
        lines += "GSC.lib\n"
        lines += "GSCAppImpl.lib\n"
        lines += "lzma.lib\n"
        lines += "zlib.lib\n"
        lines += "\n"
        
        lines += "GTJDeps库:\n"
        lines += "LogManager.lib\n"
        lines += "opencv_core2411.lib\n"
        lines += "opencv_highgui2411.lib\n"
        lines += "opencv_ml2411.lib\n"
        lines += "\n"
        
        lines += "Qt库:\n"
        lines += "Qt5PrintSupport.lib\n"
        lines += "Qt5WinExtras.lib\n"
        lines += "\n"
        
        lines += "RelWithDebInfo库:\n"
        lines += "GCLMerge.lib\n"
        lines += "GCloudUtils.lib\n"
        lines += "GCPPCalculator.lib\n"
        lines += "GGJCalcCmd.lib\n"
        lines += "GGJCalculator.lib\n"
        lines += "GGJCollect.lib\n"
        lines += "GMPDataImporter.lib\n"
        lines += "GTJCADColumnDetailIdentifier.lib\n"
        lines += "GTJCADCommonAlgorithm.lib\n"
        lines += "GTJCADFileManager.lib\n"
        lines += "GTJCADModelData.lib\n"
        lines += "GTJCADSampleCollector.lib\n"
        lines += "GTJCalcQuantityFrm.lib\n"
        lines += "GTJCalcServer.lib\n"
        lines += "GTJCloudAuth.lib\n"
        lines += "GTJQuotaCollect.lib\n"
        lines += "GTJQuotaCommon.lib\n"
        lines += "GTJQuotaReport.lib\n"
        lines += "LANCalcGroupHelper.lib\n"
        lines += "\n"
        
        file.write(lines)
    